### ISSUE TITLE
Fix API Reference header formatting for Intersphinx

### ISSUE THREAD

**Issue by analog-cbarber** [drivendataorg/cloudpathlib#211]
It would be nice if the documentation published an intersphinx `objects.inv` file so that other projects
can use it for cross linking in their documentation.

This only will require adding `enable_inventory` to the `mkdocstrings` configuration in `mkdocs.yml`:

```yaml
  - mkdocstrings:
      # generate objects.inv sphinx inventory file in site/ dir to support external cross references
      enable_inventory: true
```

See https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories
